# Generated by Django 4.2.22 on 2025-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0038_remove_complextransaction_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontypeinput',
            name='value_type',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Number'), (10, 'String'), (40, 'Date'), (100, 'Relation'), (110, 'Selector'), (120, 'Button'), (130, 'JSON')], default=20, verbose_name='value type'),
        ),
    ]
