# Generated by Django 4.2.22 on 2025-11-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0003_platformversion_created_at_and_more'),
        ('transactions', '0039_alter_transactiontypeinput_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='provider_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.providerversion', verbose_name='provider_version'),
        ),
        migrations.AddField(
            model_name='complextransaction',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.sourceversion', verbose_name='source_version'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.providerversion', verbose_name='provider_version'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.source', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.sourceversion', verbose_name='source_version'),
        ),
    ]
