# Generated by Django 4.2.22 on 2026-01-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0003_platformversion_created_at_and_more'),
        ('transactions', '0042_complextransaction_actual_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextransaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.source', verbose_name='source'),
        ),
    ]
