# Generated by Django 4.2.22 on 2026-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0043_remove_complextransaction_source_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextransaction',
            name='source_data',
            field=models.JSONField(blank=True, null=True, verbose_name='source data'),
        ),
    ]
