# Generated by Django 4.2.22 on 2025-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0009_remove_counterparty_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
    ]
