# Generated by Django 4.2.22 on 2025-11-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0002_platformversion'),
        ('instruments', '0038_accrualcalculationschedule_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualcalculationschedule',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='instrumentfactorschedule',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
    ]
