# Generated by Django 4.2.22 on 2025-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0007_remove_strategy1_created_remove_strategy1_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy1',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='strategy1',
            name='source_origin',
        ),
        migrations.RemoveField(
            model_name='strategy1',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='strategy2',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='strategy2',
            name='source_origin',
        ),
        migrations.RemoveField(
            model_name='strategy2',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='strategy3',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='strategy3',
            name='source_origin',
        ),
        migrations.RemoveField(
            model_name='strategy3',
            name='source_type',
        ),
        migrations.AddField(
            model_name='strategy1',
            name='credential_user_code',
            field=models.CharField(blank=True, help_text="Finmars Vault credential's user code used to access provider's data", max_length=1024, null=True, verbose_name='credential user code'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='credential_version_integer',
            field=models.PositiveIntegerField(default=1, help_text="Finmars Vault credential's version", verbose_name='credential integer version'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='origin_initiator_code',
            field=models.CharField(blank=True, help_text='user login (who is responsible for manual/scheduler/api call): john_doe', max_length=1024, null=True, verbose_name='origin_initiator_code'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='origin_initiator_type',
            field=models.CharField(blank=True, help_text='how action was initiated: manual, scheduler, third_party_push', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='origin_manual_entry_point',
            field=models.CharField(blank=True, help_text='exact_webpage_address (for manual only, including addons address', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='platform_task_id',
            field=models.CharField(blank=True, help_text='platform task id', max_length=1024, null=True, verbose_name='platform_task_id'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='platform_version',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of platform services (service: MAJOR.MINOR.PATCH)', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='provider_user_code',
            field=models.CharField(blank=True, help_text='Unique Identifier for this object in Provider Database', max_length=1024, null=True, verbose_name='provider user code'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='provider_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='provider_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='reference_ids',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs identifying entity in different sources, e.g. instrument ids by standards (ISIN: xxx, FIGI: yyy) and by provider/source (bank1_id: xxx, provider1_id: yyy) can be used simultaneously', verbose_name='reference_ids'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='source_user_code',
            field=models.CharField(blank=True, help_text='provider can have several sources available, e.g. Provider data_aggregator may have sources: bank1 and bank2', max_length=1024, null=True, verbose_name='source user code'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='source_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='source calendar version'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='source_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='source semantic version'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='workflow_id',
            field=models.CharField(blank=True, help_text='id or uuid', max_length=1024, null=True, verbose_name='workflow_id'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='workflow_module_user_code',
            field=models.CharField(blank=True, help_text='workflow used for the data', max_length=1024, null=True, verbose_name='workflow_module_user_code'),
        ),
        migrations.AddField(
            model_name='strategy1',
            name='workflow_module_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='workflow module semantic version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='credential_user_code',
            field=models.CharField(blank=True, help_text="Finmars Vault credential's user code used to access provider's data", max_length=1024, null=True, verbose_name='credential user code'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='credential_version_integer',
            field=models.PositiveIntegerField(default=1, help_text="Finmars Vault credential's version", verbose_name='credential integer version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='origin_initiator_code',
            field=models.CharField(blank=True, help_text='user login (who is responsible for manual/scheduler/api call): john_doe', max_length=1024, null=True, verbose_name='origin_initiator_code'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='origin_initiator_type',
            field=models.CharField(blank=True, help_text='how action was initiated: manual, scheduler, third_party_push', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='origin_manual_entry_point',
            field=models.CharField(blank=True, help_text='exact_webpage_address (for manual only, including addons address', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='platform_task_id',
            field=models.CharField(blank=True, help_text='platform task id', max_length=1024, null=True, verbose_name='platform_task_id'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='platform_version',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of platform services (service: MAJOR.MINOR.PATCH)', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='provider_user_code',
            field=models.CharField(blank=True, help_text='Unique Identifier for this object in Provider Database', max_length=1024, null=True, verbose_name='provider user code'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='provider_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='provider_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='reference_ids',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs identifying entity in different sources, e.g. instrument ids by standards (ISIN: xxx, FIGI: yyy) and by provider/source (bank1_id: xxx, provider1_id: yyy) can be used simultaneously', verbose_name='reference_ids'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='source_user_code',
            field=models.CharField(blank=True, help_text='provider can have several sources available, e.g. Provider data_aggregator may have sources: bank1 and bank2', max_length=1024, null=True, verbose_name='source user code'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='source_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='source calendar version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='source_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='source semantic version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='workflow_id',
            field=models.CharField(blank=True, help_text='id or uuid', max_length=1024, null=True, verbose_name='workflow_id'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='workflow_module_user_code',
            field=models.CharField(blank=True, help_text='workflow used for the data', max_length=1024, null=True, verbose_name='workflow_module_user_code'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='workflow_module_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='workflow module semantic version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='credential_user_code',
            field=models.CharField(blank=True, help_text="Finmars Vault credential's user code used to access provider's data", max_length=1024, null=True, verbose_name='credential user code'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='credential_version_integer',
            field=models.PositiveIntegerField(default=1, help_text="Finmars Vault credential's version", verbose_name='credential integer version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='origin_initiator_code',
            field=models.CharField(blank=True, help_text='user login (who is responsible for manual/scheduler/api call): john_doe', max_length=1024, null=True, verbose_name='origin_initiator_code'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='origin_initiator_type',
            field=models.CharField(blank=True, help_text='how action was initiated: manual, scheduler, third_party_push', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='origin_manual_entry_point',
            field=models.CharField(blank=True, help_text='exact_webpage_address (for manual only, including addons address', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='platform_task_id',
            field=models.CharField(blank=True, help_text='platform task id', max_length=1024, null=True, verbose_name='platform_task_id'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='platform_version',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of platform services (service: MAJOR.MINOR.PATCH)', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='provider_user_code',
            field=models.CharField(blank=True, help_text='Unique Identifier for this object in Provider Database', max_length=1024, null=True, verbose_name='provider user code'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='provider_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='provider_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='provider version semantic'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='reference_ids',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs identifying entity in different sources, e.g. instrument ids by standards (ISIN: xxx, FIGI: yyy) and by provider/source (bank1_id: xxx, provider1_id: yyy) can be used simultaneously', verbose_name='reference_ids'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='source_user_code',
            field=models.CharField(blank=True, help_text='provider can have several sources available, e.g. Provider data_aggregator may have sources: bank1 and bank2', max_length=1024, null=True, verbose_name='source user code'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='source_version_calendar',
            field=models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='source calendar version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='source_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='source semantic version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='workflow_id',
            field=models.CharField(blank=True, help_text='id or uuid', max_length=1024, null=True, verbose_name='workflow_id'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='workflow_module_user_code',
            field=models.CharField(blank=True, help_text='workflow used for the data', max_length=1024, null=True, verbose_name='workflow_module_user_code'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='workflow_module_version_semantic',
            field=models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='workflow module semantic version'),
        ),
    ]
