# Generated by Django 4.2.22 on 2025-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0008_remove_strategy1_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy1',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
    ]
