# Generated by Django 4.2.22 on 2025-11-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0002_platformversion'),
        ('strategies', '0011_strategy1_provider_strategy1_provider_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy1',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='strategy2',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
        migrations.AddField(
            model_name='strategy3',
            name='platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.platformversion', verbose_name='platform version'),
        ),
    ]
