# Generated by Django 4.2.22 on 2025-11-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_ecosystemdefault_license_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('version_semantic', models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='source version semantic')),
                ('version_calendar', models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='source version semantic')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_versions', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
        migrations.CreateModel(
            name='ProviderVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, help_text='Unique Code for this object. Used in Configuration and Permissions Logic', max_length=1024, null=True, verbose_name='user code')),
                ('name', models.CharField(help_text='Human Readable Name of the object', max_length=255, verbose_name='name')),
                ('short_name', models.TextField(blank=True, help_text='Short Name of the object. Used in dropdown menus', null=True, verbose_name='short name')),
                ('public_name', models.CharField(blank=True, help_text='Used if user does not have permissions to view object', max_length=255, null=True, verbose_name='public name')),
                ('notes', models.TextField(blank=True, help_text='Notes, any useful information about the object', null=True, verbose_name='notes')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified at')),
                ('version_semantic', models.CharField(blank=True, help_text='Semantic Version https://semver.org/', max_length=255, null=True, verbose_name='provider version semantic')),
                ('version_calendar', models.CharField(blank=True, help_text='Calendar Version https://calver.org/', max_length=255, null=True, verbose_name='provider version semantic')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_versions', to='users.masteruser', verbose_name='master user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member', verbose_name='owner')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provenance.provider', verbose_name='provider')),
            ],
            options={
                'verbose_name': 'provider version',
                'verbose_name_plural': 'providers versions',
                'ordering': ['user_code'],
                'abstract': False,
                'unique_together': {('master_user', 'user_code')},
            },
        ),
    ]
