# Generated by Django 4.2.22 on 2025-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0014_currencyhistory_actual_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='attributes_extra',
            field=models.JSONField(blank=True, default=dict, help_text='json-like field for different key-value pairs', verbose_name='attributes_extra'),
        ),
    ]
