# Generated by Django 4.2.22 on 2025-11-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0015_currency_attributes_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='platform_version',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='provider_version_calendar',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='provider_version_semantic',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='platform_version',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='provider_version_calendar',
        ),
        migrations.RemoveField(
            model_name='currencyhistory',
            name='provider_version_semantic',
        ),
        migrations.AddField(
            model_name='currency',
            name='origin_initiator_third_party_push_code',
            field=models.CharField(blank=True, help_text='specification for third_party_push', max_length=1024, null=True, verbose_name='origin_initiator_third_party_push_code'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='origin_initiator_third_party_push_code',
            field=models.CharField(blank=True, help_text='specification for third_party_push', max_length=1024, null=True, verbose_name='origin_initiator_third_party_push_code'),
        ),
    ]
