# Generated by Django 4.2.22 on 2025-11-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
        ('currencies', '0016_remove_currency_platform_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='currency',
            name='provider_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.providerversion', verbose_name='provider_version'),
        ),
        migrations.AddField(
            model_name='currency',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.source', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='currency',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.sourceversion', verbose_name='source_version'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.provider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='provider_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.providerversion', verbose_name='provider_version'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.source', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provenance.sourceversion', verbose_name='source_version'),
        ),
    ]
